### PR TITLE
Read mdocfile data from a string

### LINKED ISSUE #27: Read mdoc filedata from string (not filename)
Hi, I was trying to use mdocfile to read a s3 file, but I noticed that it only accepted local files as input. I was hoping that I could also pass in the raw data / string, but it didn't seem like that was an option. I was hoping that could be supported? I've created a PR to support this functionality, if it is of interest. Thank you!

### PR DESCRIPTION
**Pull request by daniel-ji**
Resolves #27. Can now call `read_string(mdoc_file_data)` in addition to `read(mdoc_file)`

### CODE REVIEW

**Comment by alisterburt** [comment]
Awesome PR, thanks so much for taking the time!

I love the class method but not so much the top level API of read_string. Could you remove it? This would give you Mdoc.from_string().as_dataframe() in your own scripts/applications which doesn't feel too onerous, what do you think? 🙂

**Comment by alisterburt** [comment]
Whoops, sorry I thought the API already had Mdoc.as_dataframe(), could you move your _read helper into that method on the Mdoc class?

**Comment by daniel-ji** [comment]
Sounds good, do you want me to remove the added documentation then? And maybe mention this new method in the documentation (or not)?

**Comment by alisterburt** [comment]
Documenting this is a good idea!👍

**Comment by daniel-ji** [comment]
Done, let me know if I should change / improve anything!

**Comment by daniel-ji** [comment]
Particularly the usage, is this okay? 

```python
from mdocfile.data_models import Mdoc

mdoc_data = ...

mdoc = Mdoc.from_string(mdoc_data).as_dataframe()
```

**Comment by alisterburt** [comment]
Looks great! In an extra section "parsing from text"

**Comment by daniel-ji** [comment]
Sounds good! I've updated the README and index.md files, let me know if I should only be changing one or if I should be adding a new page or something like that. Thanks!

**Comment by daniel-ji** [comment]
Hi, could this get merged in? And was wondering if this could be included in a release anytime soon? Thanks!

**Review by alisterburt — APPROVED** [review]
Looks great! Thank you for the PR @daniel-ji 🙂 really great work!

**Comment by alisterburt** [comment]
@daniel-ji I can push a release but it won't be for a few days at least - I'm currently on vacation 🙂 

Maybe @brisvag or @jojoelfe can push a release here? Unsure who has permissions 

(Would do it but I'm on mobile)

**Comment by jojoelfe** [comment]
I would, but doesn't look like I can...

**Comment by daniel-ji** [comment]
No worries, it can wait awhile, sorry for bothering while you're on vacation. I hope you enjoy your vacation!

**Comment by brisvag** [comment]
I pushed a tag, but we have no CI publish workflow it seems. I cannot do it manually cause I'm not maintainer on pypi, nor member of the teamtomo org there... I think we need to set up trusted publishing and all that :P

**Comment by alisterburt** [comment]
But... there is a CI publish workflow? ci.yml - i don't see the tag pushed

**Comment by brisvag** [comment]
Bizarre... There was some weirdness with git, I could see the tag on the remote and it said "all up to date" so I assume the tag was pushed. For some reason I had to explicitly use `git push upstream v0.1.3` to make it work, `--follow-tags` was not enough O.o Anyways, should be good now!

**Comment by alisterburt** [comment]
Thanks for getting back to it so fast @brisvag ! Congratulations @daniel-ji on your first PR to the project and to teamtomo, your changes have been released in v0.1.3 https://github.com/teamtomo/mdocfile/actions/runs/10419687859

**Comment by daniel-ji** [comment]
Awesome, thank you guys all so much for the quick work!

**Pull request merged**
